#ifndef PUMPKIN_ENGINE_KEY_CODE_H
#define PUMPKIN_ENGINE_KEY_CODE_H

#include <SDL3/SDL.h>
#include <cstdint>

namespace Pumpkin{
    
    enum class KeyCode : uint32_t{
        Unknown = SDL_Scancode::SDL_SCANCODE_UNKNOWN,

        A = SDL_Scancode::SDL_SCANCODE_A,
        B = SDL_Scancode::SDL_SCANCODE_B,
        C = SDL_Scancode::SDL_SCANCODE_C,
        D = SDL_Scancode::SDL_SCANCODE_D,
        E = SDL_Scancode::SDL_SCANCODE_E,
        F = SDL_Scancode::SDL_SCANCODE_F,
        G = SDL_Scancode::SDL_SCANCODE_G,
        H = SDL_Scancode::SDL_SCANCODE_H,
        I = SDL_Scancode::SDL_SCANCODE_I,
        J = SDL_Scancode::SDL_SCANCODE_J,
        K = SDL_Scancode::SDL_SCANCODE_K,
        L = SDL_Scancode::SDL_SCANCODE_L,
        M = SDL_Scancode::SDL_SCANCODE_M,
        N = SDL_Scancode::SDL_SCANCODE_N,
        O = SDL_Scancode::SDL_SCANCODE_O,
        P = SDL_Scancode::SDL_SCANCODE_P,
        Q = SDL_Scancode::SDL_SCANCODE_Q,
        R = SDL_Scancode::SDL_SCANCODE_R,
        S = SDL_Scancode::SDL_SCANCODE_S,
        T = SDL_Scancode::SDL_SCANCODE_T,
        U = SDL_Scancode::SDL_SCANCODE_U,
        V = SDL_Scancode::SDL_SCANCODE_V,
        W = SDL_Scancode::SDL_SCANCODE_W,
        X = SDL_Scancode::SDL_SCANCODE_X,
        Y = SDL_Scancode::SDL_SCANCODE_Y,
        Z = SDL_Scancode::SDL_SCANCODE_Z,

        Tilde = SDL_Scancode::SDL_SCANCODE_GRAVE,
        Minus = SDL_Scancode::SDL_SCANCODE_MINUS,
        Equals = SDL_Scancode::SDL_SCANCODE_EQUALS,
        LBracket = SDL_Scancode::SDL_SCANCODE_LEFTBRACKET,
        RBracket = SDL_Scancode::SDL_SCANCODE_RIGHTBRACKET,
        Backslash = SDL_Scancode::SDL_SCANCODE_BACKSLASH,
        Semicolon = SDL_Scancode::SDL_SCANCODE_SEMICOLON,
        Apostrophe = SDL_Scancode::SDL_SCANCODE_APOSTROPHE,
        Comma = SDL_Scancode::SDL_SCANCODE_COMMA,
        Point = SDL_Scancode::SDL_SCANCODE_PERIOD,

        Zero = SDL_Scancode::SDL_SCANCODE_0,
        One = SDL_Scancode::SDL_SCANCODE_1,
        Two = SDL_Scancode::SDL_SCANCODE_2,
        Three = SDL_Scancode::SDL_SCANCODE_3,
        Four = SDL_Scancode::SDL_SCANCODE_4,
        Five = SDL_Scancode::SDL_SCANCODE_5,
        Six = SDL_Scancode::SDL_SCANCODE_6,
        Seven = SDL_Scancode::SDL_SCANCODE_7,
        Eight = SDL_Scancode::SDL_SCANCODE_8,
        Nine = SDL_Scancode::SDL_SCANCODE_9,

        F1 = SDL_Scancode::SDL_SCANCODE_F1,
        F2 = SDL_Scancode::SDL_SCANCODE_F2,
        F3 = SDL_Scancode::SDL_SCANCODE_F3,
        F4 = SDL_Scancode::SDL_SCANCODE_F4,
        F5 = SDL_Scancode::SDL_SCANCODE_F5,
        F6 = SDL_Scancode::SDL_SCANCODE_F6,
        F7 = SDL_Scancode::SDL_SCANCODE_F7,
        F8 = SDL_Scancode::SDL_SCANCODE_F8,
        F9 = SDL_Scancode::SDL_SCANCODE_F9,
        F10 = SDL_Scancode::SDL_SCANCODE_F10,
        F11 = SDL_Scancode::SDL_SCANCODE_F11,
        F12 = SDL_Scancode::SDL_SCANCODE_F12,
        F13 = SDL_Scancode::SDL_SCANCODE_F13,
        F14 = SDL_Scancode::SDL_SCANCODE_F14,
        F15 = SDL_Scancode::SDL_SCANCODE_F15,
        F16 = SDL_Scancode::SDL_SCANCODE_F16,
        F17 = SDL_Scancode::SDL_SCANCODE_F17,
        F18 = SDL_Scancode::SDL_SCANCODE_F18,
        F19 = SDL_Scancode::SDL_SCANCODE_F19,
        F20 = SDL_Scancode::SDL_SCANCODE_F20,
        F21 = SDL_Scancode::SDL_SCANCODE_F21,
        F22 = SDL_Scancode::SDL_SCANCODE_F22,
        F23 = SDL_Scancode::SDL_SCANCODE_F23,
        F24 = SDL_Scancode::SDL_SCANCODE_F24,

        ArrowUp = SDL_Scancode::SDL_SCANCODE_UP,
        ArrowDown = SDL_Scancode::SDL_SCANCODE_DOWN,
        ArrowRight = SDL_Scancode::SDL_SCANCODE_RIGHT,
        ArrowLeft = SDL_Scancode::SDL_SCANCODE_LEFT,

        LCtrl = SDL_Scancode::SDL_SCANCODE_LCTRL,
        RCtrl = SDL_Scancode::SDL_SCANCODE_RCTRL,

        LAlt = SDL_Scancode::SDL_SCANCODE_LALT,
        RAlt = SDL_Scancode::SDL_SCANCODE_RALT,

        LShift = SDL_Scancode::SDL_SCANCODE_LSHIFT,
        RShift = SDL_Scancode::SDL_SCANCODE_RSHIFT,

        Esc = SDL_Scancode::SDL_SCANCODE_ESCAPE,
        Space = SDL_Scancode::SDL_SCANCODE_SPACE,
        Backspace = SDL_Scancode::SDL_SCANCODE_BACKSPACE,
        Tab = SDL_Scancode::SDL_SCANCODE_TAB,
        CapsLock = SDL_Scancode::SDL_SCANCODE_CAPSLOCK,

        PrintScreen = SDL_Scancode::SDL_SCANCODE_PRINTSCREEN,
        ScrollLock = SDL_Scancode::SDL_SCANCODE_SCROLLLOCK,
        Pause = SDL_Scancode::SDL_SCANCODE_PAUSE,
        Insert = SDL_Scancode::SDL_SCANCODE_INSERT,
        Home = SDL_Scancode::SDL_SCANCODE_HOME,
        End = SDL_Scancode::SDL_SCANCODE_END,
        PageUp = SDL_Scancode::SDL_SCANCODE_PAGEUP,
        PageDown = SDL_Scancode::SDL_SCANCODE_PAGEDOWN,
        Delete = SDL_Scancode::SDL_SCANCODE_DELETE,

        NumLock = SDL_Scancode::SDL_SCANCODE_NUMLOCKCLEAR,
        NPAsterisk = SDL_Scancode::SDL_SCANCODE_KP_MULTIPLY,
        NPSlash = SDL_Scancode::SDL_SCANCODE_KP_DIVIDE,
        NPPlus = SDL_Scancode::SDL_SCANCODE_KP_PLUS,
        NPMinus = SDL_Scancode::SDL_SCANCODE_KP_MINUS,
        NP0 = SDL_Scancode::SDL_SCANCODE_KP_0,
        NP1 = SDL_Scancode::SDL_SCANCODE_KP_1,
        NP2 = SDL_Scancode::SDL_SCANCODE_KP_2,
        NP3 = SDL_Scancode::SDL_SCANCODE_KP_3,
        NP4 = SDL_Scancode::SDL_SCANCODE_KP_4,
        NP5 = SDL_Scancode::SDL_SCANCODE_KP_5,
        NP6 = SDL_Scancode::SDL_SCANCODE_KP_6,
        NP7 = SDL_Scancode::SDL_SCANCODE_KP_7,
        NP8 = SDL_Scancode::SDL_SCANCODE_KP_8,
        NP9 = SDL_Scancode::SDL_SCANCODE_KP_9,
        NPPoint = SDL_Scancode::SDL_SCANCODE_KP_DECIMAL,
        NPEnter = SDL_Scancode::SDL_SCANCODE_KP_ENTER,
    };

    enum class MouseButtonCode : uint8_t{
        Left = SDL_BUTTON_LEFT,
        Middle = SDL_BUTTON_MIDDLE,
        Right = SDL_BUTTON_RIGHT,
        X1 = SDL_BUTTON_X1,
        X2 = SDL_BUTTON_X2,
    };
}

#endif